SELECT * FROM VEM_SER.PAIS ORDER BY NOME DESC;

SELECT CEP, LOGADOURO FROM VEM_SER.ENDERECO WHERE LOGADOURO LIKE 'a%' ;

SELECT * FROM VEM_SER.ENDERECO WHERE CEP LIKE '%0' ;

SELECT * FROM VEM_SER.ENDERECO WHERE NUMERO > 0 AND NUMERO < 101 ;

SELECT * FROM VEM_SER.ENDERECO WHERE LOGADOURO LIKE 'rua%' ORDER BY CEP DESC;

SELECT COUNT(*) FROM ENDERECO e;

SELECT COUNT(*) FROM ENDERECO e WHERE ID_CIDADE = 1;