CREATE TABLE VEM_SER.ESTUDANTE (
id NUMBER NOT NULL,
nome VARCHAR2(200) NOT NULL,
data_nascimento DATE NOT NULL,
nr_matricula NUMBER(10) NOT NULL,
ativo CHAR(1) NOT NULL,
PRIMARY KEY(id)
);

CREATE SEQUENCE VEM_SER.SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'joao', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'pedro', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'N');

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'paulo', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'gustavo', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'flavio', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'gusmao', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'duda', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'diana', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'mauricio', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'marcelo', TO_DATE('06-09-2001', 'dd-mm-yyyy'), '1234567891', 'S');

SELECT * FROM VEM_SER.ESTUDANTE

